### ISSUE TITLE
Crash in mbedtls when using newest HXCPP

### ISSUE THREAD

**Issue by gregdenness** [openfl/lime#1969]
Whenever I try and call HTTPRequest.load on iOS it crashes immediately and consistently. This is only when I'm using the current git versions of Lime and hxcpp (the older haxelib version of hxcpp is fine).

**Steps to reproduce:**
* clone lime from:
https://github.com/openfl/lime.git

* clone hxcpp from:
https://github.com/HaxeFoundation/hxcpp.git

* build hxcpp tools

* rebuild lime (once you have the new hxcpp):
lime rebuild ios -clean

Now run a simple test program to load a html page from a server using HTTPRequest.load, it will instantly crash with the following stack:

```
#2	0x00000002161b63d0 in pthread_mutex_destroy ()
#3	0x0000000108014ce8 in threading_mutex_free_pthread at /usr/local/lib/haxe/lib/hxcpp/dev/project/thirdparty/mbedtls-2.28.2/library/threading.c:84
#4	0x0000000108039208 in mbedtls_ctr_drbg_free at /usr/local/lib/haxe/lib/hxcpp/dev/project/thirdparty/mbedtls-2.28.2/library/ctr_drbg.c:66
#5	0x000000010821ee90 in mbedtls_close at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/vtls/mbedtls.c:980
#6	0x000000010820cc6c in cf_close at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/vtls/vtls.c:1439
#7	0x000000010820c92c in ssl_cf_close at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/vtls/vtls.c:1488
#8	0x00000001081e2db0 in Curl_conn_close at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/cfilters.c:155
#9	0x00000001081cc988 in conn_shutdown at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/url.c:749
#10	0x00000001081cc908 in Curl_disconnect at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/url.c:861
#11	0x00000001081ae744 in multi_done at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/multi.c:721
#12	0x00000001081b0b7c in multi_runsingle at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/multi.c:2078
#13	0x00000001081b038c in curl_multi_perform at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/multi.c:2690
#14	0x00000001080d2a54 in lime::lime_curl_multi_perform at /usr/local/lib/haxe/lib/lime/dev/project/src/net/curl/CURLBindings.cpp:2519
#15	0x0000000108c01afc in lime::net::curl::CURLMulti_obj::perform at /Users/gregdenness/Programming/GooseTestProject/Export/ios/GooseTestProject/haxe/build/Debug-iphoneos-64/src/lime/net/curl/CURLMulti.cpp:76
```

This works fine with the current haxelib version of hxcpp (not from git) though I've noticed that version seems to use a newer version of mbedtls (2.9) - whereas hxcpp now uses 2.28?

I've read that there we're some fixes put in a few months back to ensure that lime and hxcpp don't both use their own versions of mbedtls and that seems to be working from looking at the output library files (.a) they dont seem to be duplicating mbedtls code or anything.

I may have missed something or be doing something wrong so please forgive me if so.

Thanks,
Greg

**Comment by tobil4sk** [comment]
One thing we could try is modifying hxcpp and updating mbedtls to 2.28.10 (there is also an mbedtls 3 update PR, but it would need to be updated for current hxcpp: https://github.com/HaxeFoundation/hxcpp/pull/1113) in case this is due to some bug on the mbedtls side.

If you feel up for it you could try updating the vendored mbedtls version in hxcpp and modifying the xml files in hxcpp accordingly. If not, I can try to do it one of these next few days and send you a link to a forked branch that you could test with.

Otherwise, we could also try updating curl if that doesn't work. If neither of those work, I'm not too sure what the issue here could be, it seems now that if lime and your app are compiled with the same hxcpp version, then everything should be linked correctly.

**Comment by gregdenness** [comment]
Hi, thanks for replying. I downloaded a release of mbedtls 2.28.10 and dropped it into hxcpp and updated the xml files to link to it (made sure to remove the older version of mbedtls). Then rebuilt lime for iOS, and rebuilt my test application, but it still crashes in the same place unfortunately. I'm surprised this crashing issue on iOS wouldn't have been picked up before now, which makes me wonder if I'm doing something wrong.

Do you think it likely that the mbedtls 3 PR will get merged into hxcpp soon? Sounds like that might be where things are going and hopefully will fix this issue?

Thanks,
Greg

**Comment by tobil4sk** [comment]
> Do you think it likely that the mbedtls 3 PR will get merged into hxcpp soon? Sounds like that might be where things are going and hopefully will fix this issue?

I'm not sure exactly when it will be merged, but for now I've pushed a version of that branch with the latest hxcpp master pulled in with conflicts resolved, in case you'd like to test it: https://github.com/tobil4sk/hxcpp/tree/mbedtls3

> I'm surprised this crashing issue on iOS wouldn't have been picked up before now, which makes me wonder if I'm doing something wrong.

We investigated it a bit with @joshtynjala a while ago on discord, however, it never got reported officially on github.

**Comment by gregdenness** [comment]
Ah great thanks! I'll give it a go and see if it fixes the crash.

**Comment by gregdenness** [comment]
I pulled your new branch, rebuilt lime, rebuilt my test project and unfortunately it still crashes. It's a different crash this time, but still in mbedtls. This again happens immediately and repeatedly. 

Stack trace:

```
#0  0x00000001086867f8 in mbedtls_debug_print_msg at /usr/local/lib/haxe/lib/hxcpp/mbedtls3/project/thirdparty/mbedtls-3.6.1/library/debug.c:65
#1  0x00000001086e1a90 in mbedtls_ssl_read at /usr/local/lib/haxe/lib/hxcpp/mbedtls3/project/thirdparty/mbedtls-3.6.1/library/ssl_msg.c:5791
#2  0x00000001088be5a4 in mbedtls_close at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/vtls/mbedtls.c:970
#3  0x00000001088ac3d0 in cf_close at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/vtls/vtls.c:1439
#4  0x00000001088ac090 in ssl_cf_close at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/vtls/vtls.c:1488
#5  0x0000000108882514 in Curl_conn_close at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/cfilters.c:155
#6  0x000000010886c0ec in conn_shutdown at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/url.c:749
#7  0x000000010886c06c in Curl_disconnect at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/url.c:861
#8  0x000000010884dea8 in multi_done at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/multi.c:721
#8  0x000000010884dea8 in multi_done at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/multi.c:721
#9  0x00000001088502e0 in multi_runsingle at /usr/local/lib/haxe/lib/lime/dev/project/lib/curl/lib/multi.c:2078
```

Thanks,
Greg

**Comment by tobil4sk** [comment]
Thanks for trying it out. It may also be a bug in curl, so here I've forked off lime's develop branch and updated curl to 8.15:

https://github.com/tobil4sk/lime/tree/update-curl

**Comment by joshtynjala** [comment]
> We investigated it a bit with @joshtynjala a while ago on discord, however, it never got reported officially on github.

In that discussion, we found that hxcpp 4.3.45 is the newest hxcpp nightly build that doesn't reproduce this issue with Lime on iOS. If you'd rather use something that's newer than hxcpp 4.3.2 from Haxelib, then this may be a good option.

You can download hxcpp-4.3.45.zip here:

https://github.com/HaxeFoundation/hxcpp/releases/tag/v4.3.45

Then, install it with the command:

```sh
haxelib install hxcpp-4.3.45.zip
```

**Comment by tobil4sk** [comment]
Just had a look at the curl xml, and it looks like there was a typo which prevented the mbedtls config from being correct when compiling curl... here is a patch: #1972. Considering that 4.3.45 works, and the next testable hxcpp commit is the one that changes the xmls in hxcpp, this very well could be the cause for this crash.

**Comment by joshtynjala** [comment]
@tobil4sk That seems to fix the issue. Thank you!

I am currently running a few extra tests, but I intend to merge #1972 merge by the end of the day.

**Comment by joshtynjala** [comment]
I tested #1972 on iOS, Android, macOS, Linux, and Windows, including Neko and HL where appropriate, with the latest HXCPP (4.3.96). All native targets seem to be working properly, so I merged it into Lime develop. Closing this issue, but please follow up if it doesn't work for you, @gregdenness.

**Comment by tobil4sk** [comment]
Thanks for testing! It's nice to have finally gotten to the bottom of this
