### ISSUE TITLE
HTML5: Black window on Firefox and IE

### ISSUE THREAD

**Issue by sruloart** [openfl/lime#493]
I'm using HaxeFlixel, which adds (i.e `<assets path=...`) and embeds (but that's not relevant) two .ttf fonts as default (ariel, nokiafc22). I can't compile to html5 with the latests openfl/lime because it can't generate the .eot, .woff and .svg fonts versions (apparently). I'm not sure what's the culprit.

**Comment by Gama11** [comment]
I'm getting the same warnings, but they're just warnings - demos like Mode are still running fine for me on HTML5 (with the fonts showing up as well).

Are you sure there isn't any other error that would stop the compilation?

**Comment by sruloart** [comment]
If I delete the relevant lines in the include.xml (fonts) it compiles, so, it must be something with fonts in particular or the openfl assets in general.

**Comment by sruloart** [comment]
Also `<haxelib name="openfl" unless="create" />` so you're running bitfive?

**Comment by Gama11** [comment]
No.. what does that have to do with bitfive?

**Comment by sruloart** [comment]
Maybe I'm getting this all wrong, what's the purpose of that line?

**Comment by sruloart** [comment]
Anyhow, Mode doesn't compile for me either...the fonts do show in the compiled version (no assets paths).

**Comment by Gama11** [comment]
That line includes the openfl haxelib unless `create` is set (which is the case when you run `lime create flixel`).

**Comment by sruloart** [comment]
Right, I mistakingly took it as the old openfl backend line thingy but that's of course is removed now...it doesn't even make sense...let's just say I was horribly confused for a second :D 

How can you build Mode and I can't? I'm using Firefox, and all I see is a black window...maybe you're using the git versions of lime/openfl?

**Comment by Gama11** [comment]
If you're seeing a black window, it has already compiled succesfully. You might be getting some error in the javascript console.

No, latest releases.

**Comment by sruloart** [comment]
Hmm, you're right, the build was successful and I can see the .js files, so it must be something to do with Firefox because I can see everything on Chrome...unless you're using Firefox, in that case I have nothing :|

**Comment by jgranick** [comment]
The warning the webfont generator was not able to generate all of the webfonts. Different browsers support different font format types. This is something between "webify" and the Nokia font that's in use.

**Comment by sruloart** [comment]
@jgranick it looks like there's a bigger issue here, I've tested the html5 target with the previous and  latest lime [2.4.6] and the game object is only visible on Chrome (Firefox + IE show a black screen). Everything compiles fine now, it's just not visible for some reason.

**Comment by mrcdk** [comment]
@sruloart that's an unrelated issue, moving `ArrayBuffer` and cia. to abstracts has broken them on Firefox and IE.

**Comment by mrcdk** [comment]
OK, the issue I said before should be fixed on git.

**Comment by jgranick** [comment]
A new version with the fix has been released on haxelib as well

**Comment by sruloart** [comment]
@mrcdk I know, that was my point :D the black screen was my issue all along, the fonts were just masquerading it. +@jgranick The issue is still there, both on 2.4.7 and the git branches.

**Comment by jgranick** [comment]
Do you have any errors in the console?

**Comment by sruloart** [comment]
No, the object's (openfl-content) position is just way off: absolute; left: -10000px; top: -10000px; font-size: 300px; on Firefox and IE, if I change it to something reasonable I can see everything just fine. Weird :P

**Comment by jgranick** [comment]
I think that's an intentionally off-screen TextField used to measure text sizes

**Comment by sruloart** [comment]
###### Sorry, here's a better description of the problem/s: 

the full (weird) tag in Firefox and IE (after openfl's div and the project's script) is:
```html
<span style="position: absolute; left: -10000px; top: -10000px; font-size: 300px; font-family: "Arial",sans-serif; font-variant: normal; font-style: normal; font-weight: normal; letter-spacing: 0px;">giItT1WQy@!-/#</span>
```
Now, if I delete/change this tag in Firefox, it disappears, and the project is shown where it needs to be shown.

On IE, the tag disappears, but the project is no where to be found. It also has some issues:
>HTML1300: Navigation occurred.
File: localhost:2000
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: localhost:2000
CSS3111: @font-face encountered unknown error.
File: nokiafc22.eot
 

On Chrome, this tag doesn't appear but there's an error (it can't find the .woff font file), and a warning: "`CanvasRenderingContext2D.webkitImageSmoothingEnabled` is deprecated. Please use `CanvasRenderingContext2D.imageSmoothingEnabled` instead", but it works fine.

**Comment by jgranick** [comment]
Do the basic OpenFL samples work for you?

**Comment by sruloart** [comment]
Yep, it only happens with relation to the .eot/.woff... versions of the two default .ttf fonts of Flixel.

**Comment by jgranick** [comment]
This might not be possible to resolve, it might be good for us to (somehow) detect if font generation failed, and therefore, not try to embed those files that don't exist. However, if "webify" is not able to generate the web fonts, short of a patch to the project, I'm not sure how we get those files?

**Comment by sruloart** [comment]
I guess it's up to the user? but you don't have to generate all types, e.g. .eot support seems redundant: http://caniuse.com/#feat=eot. You can set .svg as the only font target, it looks like the best bet for successful generation & [browser support](http://caniuse.com/#search=svg). So, a flag, with fonts types to generate (if any)? 

Another issue is that IE won't load with the default .ogg files included in Flixel's [include.xml](https://github.com/HaxeFlixel/flixel/blob/dev/include.xml) :| so together with the fonts issue, I had to remove this all section in order to get IE working (it doesn't have issues with OpenFL's samples .ogg-s):
>```xml 
<assets path="assets/sounds" include="*.ogg" if="html5" unless="unit-test" />
<assets path="assets/sounds" include="*.mp3" if="flash" embed="true" />
<assets path="assets/sounds" include="*.ogg" unless="flash || html5" embed="true" />
<assets path="assets/fonts/nokiafc22.ttf" embed="true" />
<assets path="assets/fonts/arial.ttf" embed="true" unless="FLX_NO_DEBUG" />
```

cc: @Gama11...

**Comment by drinkycode** [comment]
I've been following this issue for a bit trying to figure out the Firefox preloader issue with HTML5 and I believe I've hit upon the issue. With HaxeFlixel, one of the default included fonts is Arial. In the HTML5 preloader the function checkFont attempts to see if a font has been loaded by checking if the offsetWidth of a `<span>` element has changed from the default width. Unfortunately what happens is the offsetWidth of the Arial font is (rounded) to the same size of the sans-serif in Firefox.

I got around this by adding an additional check in checkFont where we also use offsetHeight and look to see if that also differs from the default height. That looks to have solved any issues with Firefox.

**Comment by sruloart** [comment]
@drinkycode :+1: ! can confirm it's Ariel's fault :)

@jgranick so the current issues are actually :
- Fonts 
 - Firefox + IE - the issue @drinkycode describes. His fix fixes this issue entirely for Firefox.
 - IE - there's another problem with .eot generation but it doesn't cause this black screen issue.
- Sound
 - IE - It doesn't support .ogg/.wav => soundJS gets stuck because of the lack of an error listener + the lack of a fall back .mp3 files (now excluded from html5 in Flixel). There's no fix but to alert the user to:
   - use a .m4a format if he wants IE + Safari audio support (or get a .mp3 license, or ignore his need for such a license, apperantly this is how you develop for IE :| ). This would require adding type="audio/x-m4a" in the appropriate audio tag.   
    - Use a .wav format to have a fall back for Safari, and forget IE forever :D.

**Comment by starry-abyss** [comment]
Tried different samples. I can run Pirate Pig and BunnyMark (with poor performance) on Firefox 40 html5 target. NyanCat is just one still frame. HaxeFlixel samples get stuck near the end of the loading progress bar. HerokuShaders is black screen.
Running openfl: [3.3.3]

**Comment by jgranick** [comment]
I think the problem for HaxeFlixel is that it uses a default font that does not convert properly to one or two of the webfont formats, which will surely affect specific browsers -- perhaps Firefox in this case. You can open a Web Inspector to see, perhaps, if there are errors in the console?

For performance on BunnyMark (and compatibility on HerokuShaders) perhaps you should try `openfl test html5 -Dwebgl` to enable WebGL mode instead of the default canvas?

**Comment by sruloart** [comment]
Yep, I was just about ready to close this issue as soon as my debugger font HaxeFlixel's PR was to be merged, but there are some minor issues that need to be addressed first. 

My "fix" is to remove Arial.ttf and to use .m4a files instead of .oggs. Works nicely after that, but now there's the "minor" issue of FlxG.sound.play(".m4a file") won't work (you have to load the sound). Still, no black screen anymore.

**Comment by starry-abyss** [comment]
@jgranick @sruloart 
In NyanCat I get only warnings:

```
SyntaxError: unreachable code after return statement NyanCat.js:5361:1
SyntaxError: unreachable code after return statement NyanCat.js:16772:1
SyntaxError: unreachable code after return statement NyanCat.js:18878:1
SyntaxError: unreachable code after return statement NyanCat.js:26279:1
SyntaxError: unreachable code after return statement NyanCat.js:18878:1
```

In BunnyMark with -Dwebgl I get an improvement from 10 to 17 fps.
In HerokuShaders I get the following error (with or without -Dwebgl) in Firefox console:

```
SyntaxError: unreachable code after return statement HerokuShaders.js:2333:1
Main.hx:113: ERROR: 0:1: 'null' : syntax error 
 HerokuShaders.js:1738:203
```

The 1738th line of HerokuShaders.js is: `if(typeof(document) != "undefined" && (d = document.getElementById("haxe:trace")) != null) d.innerHTML += js_Boot.__unhtml(msg) + "<br/>"; else if(typeof console != "undefined" && console.log != null) console.log(msg);`

In HaxeFlixel's EZPlatformer I get something about fonts, like you said:

```
SyntaxError: unreachable code after return statement EZPlatformer.js:20378:1
SyntaxError: unreachable code after return statement EZPlatformer.js:32266:1
SyntaxError: unreachable code after return statement EZPlatformer.js:34070:1
SyntaxError: unreachable code after return statement EZPlatformer.js:40648:1
downloadable font: download failed (font-family: "Nokia Cellphone FC Small" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: http://localhost:2000/assets/fonts/nokiafc22.woff localhost:2000:29:14
downloadable font: download failed (font-family: "Arial" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: http://localhost:2000/assets/fonts/arial.woff localhost:2000:39:14
downloadable font: OS/2: Bad usWidthClass: 0, changing it to: 1 (font-family: "Nokia Cellphone FC Small" style:normal weight:normal stretch:normal src index:3) source: http://localhost:2000/assets/fonts/nokiafc22.ttf localhost:2000:29:14
```

@sruloart 
Removing Arial.ttf from 'EZPlatformer\export\html5\bin' after build before running? It doesn't seem to help, I still get .woff errors

**Comment by jgranick** [comment]
@starry-abyss What are you testing on? I just reduced the number of "unreachable code" warnings with a few commits, these all work on Firefox for me, and BunnyMark does lots of bunnies on WebGL at 60 FPS here :smile:

**Comment by sruloart** [comment]
Can confirm everything checks out fine on this end too (latests Lime/Openfl/Haxe releases, win10, GTX960OC). That shaders' demo is really cool BTW :) 

@starry-abyss, you better reset your entire Haxe setup, something is definitely wrong with your haxelib and/or your system (GPU drivers maybe, but can be just about anything). By "reset" I mean wipe everything from your disk and reinstall Haxe and the necessary libraries. 

As for making the HaxeFlixel demos to work with html5 after you purge your Haxe setup, look at my comments here and on my PR over the Flixel's repo. @jgranick latest PR is also worth checking out to have the best results. 

If the problem persists then check your system for problems, like viruses and what not.

**Comment by starry-abyss** [comment]
@jgranick GTX660, Win 7 Home Premium 64bit, Firefox 40. I uninstalled the haxe toolkit entirely and did a fresh install of openfl, lime, flixel and flixel-tools (and ran setup where possible).
There is a checkbox in Firefox settings that reads something like "Use hardware acceleration when possible". After checking it and restarting the browser I get 60 fps in BunnyMark though sometimes it's jerky.
@sruloart I don't think drivers are the case as I can run any sample (including HerokuShaders) on neko target without issues.

BUT!

For NyanCat I still get only one still frame (the cat must run).
For HerokuShaders I still get exactly the same syntax error (but warnings are gone).
I commented out those lines in HaxeFlixel's include.xml:

```
<assets path="assets/fonts/nokiafc22.ttf" embed="true" />
<assets path="assets/fonts/arial.ttf" embed="true" unless="FLX_NO_DEBUG" />
```

And now I have a running the "EZPlatformer" game, but it's broken, it's not a platformer anymore :D 

![platformer](https://cloud.githubusercontent.com/assets/11571820/10025350/7e7ea696-6164-11e5-8da2-fa6d939c30e8.gif)

Should I post it in HaxeFlixel repo too?
Also, @sruloart, what PRs are you referring to?
