### ISSUE TITLE
Error: Could not find haxelib "flixel"

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#986]
Something seems to be wrong since Lime bundles Haxelib (5.0.0)... I was trying to test https://github.com/HaxeFlixel/flixel/pull/2068:

```
> lime test neko
Error: Could not find haxelib "flixel", does it need to be installed?
```

Haxelib path / list (of the _actual_ haxelib) works fine:

```
> haxelib path flixel
C:\HaxeToolkit\haxe\lib\flixel/git/
-D flixel=4.3.0
-L C:\HaxeToolkit\haxe\lib\lime/5,0,0/ndll/
--macro lime.Lib.extraParams()
C:\HaxeToolkit\haxe\lib\lime/5,0,0/
-D lime=5.0.0
--macro openfl._internal.utils.ExtraParams.include()
C:\HaxeToolkit\haxe\lib\openfl/5,1,1/
-D openfl=5.1.1

> haxelib list flixel
flixel: 4.2.1 [git]
```

Trying to run the `haxelib.n` bundled with Lime, I get an error, but I'm not sure if it's valid to run it like this to begin with:

```
> neko C:\HaxeToolkit\haxe\lib\lime\5,0,0\tools\haxelib.n path flixel
Error: Invalid field access : length
```

**Comment by bendmorris** [comment]
To piggyback, I'm having import issues on 5.x which I'm guessing might be related. After including tink_macro in project.xml I get `Type not found : tink.macro.Exprs` only when using Lime 5.x. Someone is also reporting "[flash package not found](https://github.com/HaxePunk/HaxePunk/issues/487)" on HaxePunk which may or may not be related.

I was surprised to learn that Lime is now bundling haxelib, which seems like a big expansion in scope. What was the reasoning?

**Comment by man2** [comment]
and it also breaks how path works in HaxeDevelop also, I can't include other library other than openfl / lime

**Comment by Beeblerox** [comment]
i can confirm that latest lime release on haxelib breaks HaxeDevelop. I get the same error message as @man2 Every time i try to open or compile project with it, or even open project settings.

**Comment by guruas3** [comment]
+1 can't compile with lime 5.0

**Comment by jgranick** [comment]
@Gama11 Could you tell me more about your system? What version of Haxe, how is it installed, does it have special environment variables defined, and which branch/version of Flixel?

```bash
C:\Development\Haxe\flixel-demos\Platformers\Mode>neko C:\HaxeToolkit\haxe\lib\lime\5,0,0\tools\haxelib.n path flixel
C:\Development\Haxe\flixel\
-D flixel=4.3.0
-L C:\HaxeToolkit\haxe\lib\lime/5,0,0/ndll/
--macro lime.Lib.extraParams()
C:\HaxeToolkit\haxe\lib\lime/5,0,0/
-D lime=5.0.0
--macro openfl._internal.utils.ExtraParams.include()
C:\HaxeToolkit\haxe\lib\openfl/5,1,1/
-D openfl=5.1.1
```

@man2, @Beeblerox, do you know what HaxeDevelop is doing when it throws this error? What command is running?

@bendmorris Do you know a way I could reproduce your use-case on my end? Are there existing Tink samples I could run?

**Comment by bendmorris** [comment]
I was able to reproduce this in the "UsingBitmapData" sample by adding `<haxelib name="tink_macro"/>` to project.xml and the following to Source/Main.hx:

```
#if macro
using tink.MacroApi;
#end

...

    public function new() {

        ...

        trace(abc());
    }

    macro static function abc()
    {
        return 1.toExpr();
    }
```

Works with OpenFL 5.0.0/Lime 4.1.0 and traces "1".  With OpenFL 5.5.1/Lime 5.0.0 I get:

```
Source/Main.hx:13: characters 0-20 : Type not found : tink.MacroApi
Source/Main.hx:16: lines 16-108 : Defined in this class
```

**Comment by jgranick** [comment]
Thanks guys, I believe all these issues are resolved with Lime 5.0.1, which has just been released.

Please let me know if you continue to see anything irregular, thanks again 😄

**Comment by Gama11** [comment]
I'm still having some issues when trying to build a Flixel project:

```
--macro:1: character 0 : Type not found : flixel.system.macros.FlxDefines
```

Output of `haxelib path flixel` now seems identical for real and fake Haxelib though.

**Comment by Gama11** [comment]
Ok, that appears to be fixed by the latest commit (8d4b5151b5e15109c0d9cd908dce808ad4db35f8).
